feat(config): added initial keyring support (#83)
UpCloudLtd/upcloud-cli pull request #350
Opened 2024-12-30 20:58 UTC by MarinX

This PR adds initial support for the keyring.
I used [zalando/go-keyring](https://github.com/zalando/go-keyring) because of recent commits on repo (compared to [99designs/keyring](https://github.com/99designs/keyring)).
When I say initial, I mean it's open for discussion and adding more features (create auth command and save it to keyring?).

How it works:
If a username is set and the password is empty, check the keyring for service `upctl` where the username is coming either from the config file or env.
This type of logic does not break current.

Problem:
This PR does not read the username from the keyring, so it still needs a username from config or env. Maybe to introduce a config command `--keyring` ?

For me, it works by using UPCLOUD_USERNAME and creating username/password upctl services on keyring so I can switch easily between accounts without providing passwords.

2024-12-31 14:53 UTC, kangasta commented
Thanks for the pull request! We'll do some testing with this and let's discuss what would be the best approach to get this merged.

We are also working on adding tokens support for authentication ([product radar](https://upcloud.com/docs/product-radar/)), so probably best to start with minimal implementation, like you described above, and add more features once the initial functionality is on the main.

2025-01-02 08:52 UTC, scop commented on internal/config/config.go
> +		password, err := keyring.Get("upctl", v.GetString("username"))
Just one quick nitty comment based on skimming, not a full review: let's extract the service name to a constant, and reuse in the missing_credentials.go message and tests.

2025-01-14 20:35 UTC, kangasta requested changes
Did some testing with this and seems to work nicely on mac 👍 We'll have to still confirm that this does not have conflicts with the upcoming API tokens feature.

Added one comment about the unittest and seems that at least the ubuntu test workflow needs a step for installing keyring support. I guess something like the snippet below would work for that 🤔

```yaml
- name: Install keyring test dependencies on Ubuntu
  run: apt install gnome-keyring
  if: matrix.os == 'ubuntu-latest'
```

2025-01-14 20:35 UTC, kangasta commented on internal/config/config_test.go
> +	err = keyring.Set("upctl", "sdkfo", "foo")
This will end up in the systems default keyring, so could use more descriptive username, e.g `unittest`, and a cleanup function for removing this with [t.Cleanup](https://pkg.go.dev/testing@master#T.Cleanup).

2025-01-15 08:51 UTC, MarinX commented on internal/config/config_test.go
> +	err = keyring.Set("upctl", "sdkfo", "foo")
will do. I will update the docker image and test it before pushing. Keep you posted.

2025-01-17 17:19 UTC, MarinX commented on internal/config/config_test.go
> +	err = keyring.Set("upctl", "sdkfo", "foo")
docker image updated: took a sample from [go-keyring](https://github.com/zalando/go-keyring/blob/master/.github/workflows/go.yml)
cleanup implemented: clean only the test user that was set

2025-02-26 10:23 UTC, kangasta commented
We now have the initial token support available in [v3.15.0](https://github.com/UpCloudLtd/upcloud-cli/releases/tag/v3.15.0), so I added option to read token from the keyring when no credentials are defined. I also changed the service name to `UpCloud` as we probably want to utilize the keyring in our other tooling later as well.

2025-02-26 12:32 UTC, kangasta approved these changes

2025-02-26 13:16 UTC, villevsv-upcloud approved these changes
Tested locally on Linux with Kwallet.

2025-02-26 13:42 UTC, merged